# Generated by Django 2.1.7 on 2019-10-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20191010_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='签名'),
        ),
    ]
