# Generated by Django 2.1.7 on 2019-10-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_user_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='head_img',
            field=models.TextField(blank=True, null=True, verbose_name='用户图像'),
        ),
    ]
