# Generated by Django 2.1.7 on 2019-10-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20191011_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': '职位表', 'verbose_name_plural': '职位表'},
        ),
    ]
