# Generated by Django 2.1.7 on 2019-10-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_auto_20191012_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='is_menu',
        ),
        migrations.AddField(
            model_name='permission',
            name='type',
            field=models.IntegerField(choices=[(1, '菜单'), (2, '按钮'), (3, '接口')], default=1, verbose_name='类型'),
            preserve_default=False,
        ),
    ]
