# Generated by Django 2.1.7 on 2019-10-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0010_auto_20191014_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='menu',
        ),
        migrations.AddField(
            model_name='permission',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='permission',
            name='menu_icon',
            field=models.CharField(default='', max_length=64, verbose_name='菜单图标'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='上级菜单ID'),
        ),
        migrations.AddField(
            model_name='permission',
            name='u_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
