# Generated by Django 2.1.7 on 2019-10-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0011_auto_20191014_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='authority',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='权限标识'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='menu_icon',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='菜单图标'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='parent_id',
            field=models.IntegerField(blank=True, default=-1, null=True, verbose_name='上级菜单ID'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='URL'),
        ),
    ]
