# Generated by Django 2.1.7 on 2019-10-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0012_auto_20191014_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='type',
        ),
        migrations.AddField(
            model_name='permission',
            name='per_type',
            field=models.IntegerField(choices=[(0, '菜单'), (1, '按钮'), (2, '接口')], default=0, verbose_name='权限类型'),
            preserve_default=False,
        ),
    ]
