# Generated by Django 2.1.7 on 2019-10-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0014_auto_20191014_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='order_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='序号'),
        ),
    ]
